[tool.poetry]
name = "sittube"
version = "0.1.0"
description = ""
authors = ["Álvaro Troya <alvaro.troya@googlemail.com>"]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.11"
tqdm = "^4.66.2"
pydantic = "1.10"
ruff = "^0.4.1"
opencv-python = "^4.9.0.80"
numpy = "^1.26.4"
fastapi = "^0.110.2"
uvicorn = {extras = ["standard"], version = "^0.29.0"}
pathlib = "^1.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
